module.exports =
{
   CONST_CANVAS_HEIGHT,
   CONST_CANVAS_WIDTH,
   CONST_DIM_LARGE,
   CONST_DIM_MEDIUM,
   CONST_DIM_XLARGE,
   CONST_ENVIRONMENT_I84, // TODO: why isn't this necessary?
   CONST_FALSE,
   CONST_FONT_SIZE_TINY,
   CONST_LANE_0_BASE,
   CONST_LANE_0_INDEX,
   CONST_LANE_1_INDEX,
   CONST_LANE_2_INDEX,
   CONST_LANE_3_INDEX,
   CONST_LANE_4_INDEX,
   CONST_LANE_HEIGHT,
   CONST_TRUE
};
