// Jest includes:
const each = require('jest-each').default;

// Constant includes:
const constants          = require('./environment/constants');
const kAlabama           = constants.kAlabama;
const kAlaskaMainland    = constants.kAlaskaMainland;
const kArizona           = constants.kArizona;
const kArkansas          = constants.kArkansas;
const kCalifornia        = constants.kCalifornia;
const kColorado          = constants.kColorado;
const kConnecticut       = constants.kConnecticut;
const kDelaware          = constants.kDelaware;
const kFlorida           = constants.kFlorida;
const kGeorgia           = constants.kGeorgia;
const kHawaii            = constants.kHawaii;
const kIllinois          = constants.kIllinois;
const kIndiana           = constants.kIndiana;
const kIowa              = constants.kIowa;
const kKansas            = constants.kKansas;
const kKauai             = constants.kKauai;
const kKentucky          = constants.kKentucky;
const kKodiakIsland      = constants.kKodiakIsland;
const kLouisiana         = constants.kLouisiana;
const kMaine             = constants.kMaine;
const kMaryland          = constants.kMaryland;
const kMassachusetts     = constants.kMassachusetts;
const kMaui              = constants.kMaui;
const kMichiganMainland  = constants.kMichiganMainland;
const kMichiganPeninsula = constants.kMichiganPeninsula;
const kMinnesota         = constants.kMinnesota;
const kMississippi       = constants.kMississippi;
const kMissouri          = constants.kMissouri;
const kMontana           = constants.kMontana;
const kNebraska          = constants.kNebraska;
const kNevada            = constants.kNevada;
const kNewJersey         = constants.kNewJersey;
const kNewHampshire      = constants.kNewHampshire;
const kNewMexico         = constants.kNewMexico;
const kNewYork           = constants.kNewYork;
const kNorthCarolina     = constants.kNorthCarolina;
const kNorthDakota       = constants.kNorthDakota;
const kOahu              = constants.kOahu;
const kOhio              = constants.kOhio;
const kOklahoma          = constants.kOklahoma;
const kOregon            = constants.kOregon;
const kPennsylvania      = constants.kPennsylvania;
const kPrefixRedState    = constants.kPrefixRedState;
const kRhodeIsland       = constants.kRhodeIsland;
const kSouthCarolina     = constants.kSouthCarolina;
const kSouthDakota       = constants.kSouthDakota;
const kTennessee         = constants.kTennessee;
const kTexas             = constants.kTexas;
const kUtah              = constants.kUtah;
const kVermont           = constants.kVermont;
const kVirginia          = constants.kVirginia;
const kWestVirginia      = constants.kWestVirginia;
const kWisconsin         = constants.kWisconsin;

// Map Function includes:
const mapFunctions = require('./environment/mapFunctions');
const onPageLoad
    = mapFunctions.onPageLoad;
const tomHasHighPointedStateWithinSliderRange
    = mapFunctions.tomHasHighPointedStateWithinSliderRange;

// Test Constant includes:
const testConstants = require('./resources/testConstants');
const kIdaho                    = testConstants.kIdaho;
const kWashington               = testConstants.kWashington;
const kWyoming                  = testConstants.kWyoming;
const kYearSliderValueAfter2014 = testConstants.kYearSliderValueAfter2014;
const kYearSliderValueAfter2015 = testConstants.kYearSliderValueAfter2015;
const kYearSliderValueAfter2016 = testConstants.kYearSliderValueAfter2016;
const kYearSliderValueAfter2017 = testConstants.kYearSliderValueAfter2017;
const kYearSliderValueAfter2018 = testConstants.kYearSliderValueAfter2018;
const kYearSliderValueAfter2019 = testConstants.kYearSliderValueAfter2019;
const kYearSliderValueAfter2020 = testConstants.kYearSliderValueAfter2020;
const kYearSliderValueAfter2021 = testConstants.kYearSliderValueAfter2021;
const kYearSliderValueAfter2022 = testConstants.kYearSliderValueAfter2022;
const kYearSliderValueAfter2023 = testConstants.kYearSliderValueAfter2023;
const kYearSliderValueAfter2024 = testConstants.kYearSliderValueAfter2024;

// Test Function includes:
const testFunctions = require('./resources/testFunctions');
const changeValueOfSliderThumb = testFunctions.changeValueOfSliderThumb;

const kInputAndExpectedOutputSets = [
    [kYearSliderValueAfter2024, null,               false],
    [kYearSliderValueAfter2024, undefined,          false],
    [kYearSliderValueAfter2024, kAlabama,           true ],
    [kYearSliderValueAfter2024, kAlaskaMainland,    false],
    [kYearSliderValueAfter2024, kArizona,           true ],
    [kYearSliderValueAfter2024, kArkansas,          true ],
    [kYearSliderValueAfter2024, kCalifornia,        true ],
    [kYearSliderValueAfter2024, kColorado,          true ],
    [kYearSliderValueAfter2024, kConnecticut,       true ],
    [kYearSliderValueAfter2024, kDelaware,          true ],
    [kYearSliderValueAfter2024, kFlorida,           false],
    [kYearSliderValueAfter2024, kGeorgia,           true ],
    [kYearSliderValueAfter2024, kHawaii,            false],
    [kYearSliderValueAfter2024, kIdaho,             false],
    [kYearSliderValueAfter2024, kIllinois,          true ],
    [kYearSliderValueAfter2024, kIndiana,           true ],
    [kYearSliderValueAfter2024, kIowa,              true ],
    [kYearSliderValueAfter2024, kKansas,            true ],
    [kYearSliderValueAfter2024, kKauai,             false],
    [kYearSliderValueAfter2024, kKentucky,          true ],
    [kYearSliderValueAfter2024, kKodiakIsland,      false],
    [kYearSliderValueAfter2024, kLouisiana,         true ],
    [kYearSliderValueAfter2024, kMaine,             true ],
    [kYearSliderValueAfter2024, kMaryland,          true ],
    [kYearSliderValueAfter2024, kMassachusetts,     true ],
    [kYearSliderValueAfter2024, kMaui,              false],
    [kYearSliderValueAfter2024, kMichiganMainland,  true ],
    [kYearSliderValueAfter2024, kMichiganPeninsula, true ],
    [kYearSliderValueAfter2024, kMinnesota,         true ],
    [kYearSliderValueAfter2024, kMississippi,       true ],
    [kYearSliderValueAfter2024, kMissouri,          true ],
    [kYearSliderValueAfter2024, kMontana,           false],
    [kYearSliderValueAfter2024, kNebraska,          true ],
    [kYearSliderValueAfter2024, kNevada,            true ],
    [kYearSliderValueAfter2024, kNewHampshire,      true ],
    [kYearSliderValueAfter2024, kNewJersey,         true ],
    [kYearSliderValueAfter2024, kNewMexico,         true ],
    [kYearSliderValueAfter2024, kNewYork,           true ],
    [kYearSliderValueAfter2024, kNorthCarolina,     true ],
    [kYearSliderValueAfter2024, kNorthDakota,       true ],
    [kYearSliderValueAfter2024, kOahu,              false],
    [kYearSliderValueAfter2024, kOhio,              true ],
    [kYearSliderValueAfter2024, kOklahoma,          true ],
    [kYearSliderValueAfter2024, kOregon,            false],
    [kYearSliderValueAfter2024, kPennsylvania,      true ],
    [kYearSliderValueAfter2024, kRhodeIsland,       true ],
    [kYearSliderValueAfter2024, kSouthCarolina,     true ],
    [kYearSliderValueAfter2024, kSouthDakota,       true ],
    [kYearSliderValueAfter2024, kTennessee,         true ],
    [kYearSliderValueAfter2024, kTexas,             true ],
    [kYearSliderValueAfter2024, kUtah,              true ],
    [kYearSliderValueAfter2024, kVermont,           true ],
    [kYearSliderValueAfter2024, kVirginia,          true ],
    [kYearSliderValueAfter2024, kWashington,        false],
    [kYearSliderValueAfter2024, kWestVirginia,      true ],
    [kYearSliderValueAfter2024, kWisconsin,         true ],
    [kYearSliderValueAfter2024, kWyoming,           false],
    [kYearSliderValueAfter2023, null,               false],
    [kYearSliderValueAfter2023, undefined,          false],
    [kYearSliderValueAfter2023, kAlabama,           true ],
    [kYearSliderValueAfter2023, kAlaskaMainland,    false],
    [kYearSliderValueAfter2023, kArizona,           true ],
    [kYearSliderValueAfter2023, kArkansas,          true ],
    [kYearSliderValueAfter2023, kCalifornia,        true ],
    [kYearSliderValueAfter2023, kColorado,          true ],
    [kYearSliderValueAfter2023, kConnecticut,       true ],
    [kYearSliderValueAfter2023, kDelaware,          true ],
    [kYearSliderValueAfter2023, kFlorida,           false],
    [kYearSliderValueAfter2023, kGeorgia,           true ],
    [kYearSliderValueAfter2023, kHawaii,            false],
    [kYearSliderValueAfter2023, kIdaho,             false],
    [kYearSliderValueAfter2023, kIllinois,          true ],
    [kYearSliderValueAfter2023, kIndiana,           true ],
    [kYearSliderValueAfter2023, kIowa,              true ],
    [kYearSliderValueAfter2023, kKansas,            true ],
    [kYearSliderValueAfter2023, kKauai,             false],
    [kYearSliderValueAfter2023, kKentucky,          true ],
    [kYearSliderValueAfter2023, kKodiakIsland,      false],
    [kYearSliderValueAfter2023, kLouisiana,         true ],
    [kYearSliderValueAfter2023, kMaine,             true ],
    [kYearSliderValueAfter2023, kMaryland,          true ],
    [kYearSliderValueAfter2023, kMassachusetts,     true ],
    [kYearSliderValueAfter2023, kMaui,              false],
    [kYearSliderValueAfter2023, kMichiganMainland,  true ],
    [kYearSliderValueAfter2023, kMichiganPeninsula, true ],
    [kYearSliderValueAfter2023, kMinnesota,         true ],
    [kYearSliderValueAfter2023, kMississippi,       true ],
    [kYearSliderValueAfter2023, kMissouri,          true ],
    [kYearSliderValueAfter2023, kMontana,           false],
    [kYearSliderValueAfter2023, kNebraska,          true ],
    [kYearSliderValueAfter2023, kNevada,            false],
    [kYearSliderValueAfter2023, kNewHampshire,      true ],
    [kYearSliderValueAfter2023, kNewJersey,         true ],
    [kYearSliderValueAfter2023, kNewMexico,         true ],
    [kYearSliderValueAfter2023, kNewYork,           true ],
    [kYearSliderValueAfter2023, kNorthCarolina,     true ],
    [kYearSliderValueAfter2023, kNorthDakota,       true ],
    [kYearSliderValueAfter2023, kOahu,              false],
    [kYearSliderValueAfter2023, kOhio,              true ],
    [kYearSliderValueAfter2023, kOklahoma,          true ],
    [kYearSliderValueAfter2023, kOregon,            false],
    [kYearSliderValueAfter2023, kPennsylvania,      true ],
    [kYearSliderValueAfter2023, kRhodeIsland,       true ],
    [kYearSliderValueAfter2023, kSouthCarolina,     true ],
    [kYearSliderValueAfter2023, kSouthDakota,       true ],
    [kYearSliderValueAfter2023, kTennessee,         true ],
    [kYearSliderValueAfter2023, kTexas,             true ],
    [kYearSliderValueAfter2023, kUtah,              true ],
    [kYearSliderValueAfter2023, kVermont,           true ],
    [kYearSliderValueAfter2023, kVirginia,          true ],
    [kYearSliderValueAfter2023, kWashington,        false],
    [kYearSliderValueAfter2023, kWestVirginia,      true ],
    [kYearSliderValueAfter2023, kWisconsin,         true ],
    [kYearSliderValueAfter2023, kWyoming,           false],
    [kYearSliderValueAfter2022, null,               false],
    [kYearSliderValueAfter2022, undefined,          false],
    [kYearSliderValueAfter2022, kAlabama,           true ],
    [kYearSliderValueAfter2022, kAlaskaMainland,    false],
    [kYearSliderValueAfter2022, kArizona,           true ],
    [kYearSliderValueAfter2022, kArkansas,          true ],
    [kYearSliderValueAfter2022, kCalifornia,        true ],
    [kYearSliderValueAfter2022, kColorado,          true ],
    [kYearSliderValueAfter2022, kConnecticut,       true ],
    [kYearSliderValueAfter2022, kDelaware,          true ],
    [kYearSliderValueAfter2022, kFlorida,           false],
    [kYearSliderValueAfter2022, kGeorgia,           true ],
    [kYearSliderValueAfter2022, kHawaii,            false],
    [kYearSliderValueAfter2022, kIdaho,             false],
    [kYearSliderValueAfter2022, kIllinois,          true ],
    [kYearSliderValueAfter2022, kIndiana,           true ],
    [kYearSliderValueAfter2022, kIowa,              true ],
    [kYearSliderValueAfter2022, kKansas,            true ],
    [kYearSliderValueAfter2022, kKauai,             false],
    [kYearSliderValueAfter2022, kKentucky,          true ],
    [kYearSliderValueAfter2022, kKodiakIsland,      false],
    [kYearSliderValueAfter2022, kLouisiana,         true ],
    [kYearSliderValueAfter2022, kMaine,             true ],
    [kYearSliderValueAfter2022, kMaryland,          true ],
    [kYearSliderValueAfter2022, kMassachusetts,     true ],
    [kYearSliderValueAfter2022, kMaui,              false],
    [kYearSliderValueAfter2022, kMichiganMainland,  true ],
    [kYearSliderValueAfter2022, kMichiganPeninsula, true ],
    [kYearSliderValueAfter2022, kMinnesota,         true ],
    [kYearSliderValueAfter2022, kMississippi,       true ],
    [kYearSliderValueAfter2022, kMissouri,          true ],
    [kYearSliderValueAfter2022, kMontana,           false],
    [kYearSliderValueAfter2022, kNebraska,          true ],
    [kYearSliderValueAfter2022, kNevada,            false],
    [kYearSliderValueAfter2022, kNewHampshire,      true ],
    [kYearSliderValueAfter2022, kNewJersey,         true ],
    [kYearSliderValueAfter2022, kNewMexico,         true ],
    [kYearSliderValueAfter2022, kNewYork,           true ],
    [kYearSliderValueAfter2022, kNorthCarolina,     false],
    [kYearSliderValueAfter2022, kNorthDakota,       true ],
    [kYearSliderValueAfter2022, kOahu,              false],
    [kYearSliderValueAfter2022, kOhio,              true ],
    [kYearSliderValueAfter2022, kOklahoma,          true ],
    [kYearSliderValueAfter2022, kOregon,            false],
    [kYearSliderValueAfter2022, kPennsylvania,      true ],
    [kYearSliderValueAfter2022, kRhodeIsland,       true ],
    [kYearSliderValueAfter2022, kSouthCarolina,     true ],
    [kYearSliderValueAfter2022, kSouthDakota,       true ],
    [kYearSliderValueAfter2022, kTennessee,         true ],
    [kYearSliderValueAfter2022, kTexas,             true ],
    [kYearSliderValueAfter2022, kUtah,              true ],
    [kYearSliderValueAfter2022, kVermont,           true ],
    [kYearSliderValueAfter2022, kVirginia,          false],
    [kYearSliderValueAfter2022, kWashington,        false],
    [kYearSliderValueAfter2022, kWestVirginia,      true ],
    [kYearSliderValueAfter2022, kWisconsin,         true ],
    [kYearSliderValueAfter2022, kWyoming,           false],
    [kYearSliderValueAfter2021, null,               false],
    [kYearSliderValueAfter2021, undefined,          false],
    [kYearSliderValueAfter2021, kAlabama,           true ],
    [kYearSliderValueAfter2021, kAlaskaMainland,    false],
    [kYearSliderValueAfter2021, kArizona,           true ],
    [kYearSliderValueAfter2021, kArkansas,          true ],
    [kYearSliderValueAfter2021, kCalifornia,        true ],
    [kYearSliderValueAfter2021, kColorado,          true ],
    [kYearSliderValueAfter2021, kConnecticut,       true ],
    [kYearSliderValueAfter2021, kDelaware,          true ],
    [kYearSliderValueAfter2021, kFlorida,           false],
    [kYearSliderValueAfter2021, kGeorgia,           true ],
    [kYearSliderValueAfter2021, kHawaii,            false],
    [kYearSliderValueAfter2021, kIdaho,             false],
    [kYearSliderValueAfter2021, kIllinois,          true ],
    [kYearSliderValueAfter2021, kIndiana,           true ],
    [kYearSliderValueAfter2021, kIowa,              false],
    [kYearSliderValueAfter2021, kKansas,            true ],
    [kYearSliderValueAfter2021, kKauai,             false],
    [kYearSliderValueAfter2021, kKentucky,          true ],
    [kYearSliderValueAfter2021, kKodiakIsland,      false],
    [kYearSliderValueAfter2021, kLouisiana,         true ],
    [kYearSliderValueAfter2021, kMaine,             true ],
    [kYearSliderValueAfter2021, kMaryland,          true ],
    [kYearSliderValueAfter2021, kMassachusetts,     true ],
    [kYearSliderValueAfter2021, kMaui,              false],
    [kYearSliderValueAfter2021, kMichiganMainland,  true ],
    [kYearSliderValueAfter2021, kMichiganPeninsula, true ],
    [kYearSliderValueAfter2021, kMinnesota,         true ],
    [kYearSliderValueAfter2021, kMississippi,       true ],
    [kYearSliderValueAfter2021, kMissouri,          false],
    [kYearSliderValueAfter2021, kMontana,           false],
    [kYearSliderValueAfter2021, kNebraska,          true ],
    [kYearSliderValueAfter2021, kNevada,            false],
    [kYearSliderValueAfter2021, kNewHampshire,      true ],
    [kYearSliderValueAfter2021, kNewJersey,         true ],
    [kYearSliderValueAfter2021, kNewMexico,         true ],
    [kYearSliderValueAfter2021, kNewYork,           true ],
    [kYearSliderValueAfter2021, kNorthCarolina,     false],
    [kYearSliderValueAfter2021, kNorthDakota,       true ],
    [kYearSliderValueAfter2021, kOahu,              false],
    [kYearSliderValueAfter2021, kOhio,              true ],
    [kYearSliderValueAfter2021, kOklahoma,          true ],
    [kYearSliderValueAfter2021, kOregon,            false],
    [kYearSliderValueAfter2021, kPennsylvania,      true ],
    [kYearSliderValueAfter2021, kRhodeIsland,       true ],
    [kYearSliderValueAfter2021, kSouthCarolina,     true ],
    [kYearSliderValueAfter2021, kSouthDakota,       true ],
    [kYearSliderValueAfter2021, kTennessee,         true ],
    [kYearSliderValueAfter2021, kTexas,             true ],
    [kYearSliderValueAfter2021, kUtah,              false],
    [kYearSliderValueAfter2021, kVermont,           true ],
    [kYearSliderValueAfter2021, kVirginia,          false],
    [kYearSliderValueAfter2021, kWashington,        false],
    [kYearSliderValueAfter2021, kWestVirginia,      true ],
    [kYearSliderValueAfter2021, kWisconsin,         true ],
    [kYearSliderValueAfter2021, kWyoming,           false],
    [kYearSliderValueAfter2020, null,               false],
    [kYearSliderValueAfter2020, undefined,          false],
    [kYearSliderValueAfter2020, kAlabama,           false],
    [kYearSliderValueAfter2020, kAlaskaMainland,    false],
    [kYearSliderValueAfter2020, kArizona,           true ],
    [kYearSliderValueAfter2020, kArkansas,          true ],
    [kYearSliderValueAfter2020, kCalifornia,        false],
    [kYearSliderValueAfter2020, kColorado,          true ],
    [kYearSliderValueAfter2020, kConnecticut,       true ],
    [kYearSliderValueAfter2020, kDelaware,          true ],
    [kYearSliderValueAfter2020, kFlorida,           false],
    [kYearSliderValueAfter2020, kGeorgia,           true ],
    [kYearSliderValueAfter2020, kHawaii,            false],
    [kYearSliderValueAfter2020, kIdaho,             false],
    [kYearSliderValueAfter2020, kIllinois,          true ],
    [kYearSliderValueAfter2020, kIndiana,           true ],
    [kYearSliderValueAfter2020, kIowa,              false],
    [kYearSliderValueAfter2020, kKansas,            true ],
    [kYearSliderValueAfter2020, kKauai,             false],
    [kYearSliderValueAfter2020, kKentucky,          true ],
    [kYearSliderValueAfter2020, kKodiakIsland,      false],
    [kYearSliderValueAfter2020, kLouisiana,         true ],
    [kYearSliderValueAfter2020, kMaine,             true ],
    [kYearSliderValueAfter2020, kMaryland,          true ],
    [kYearSliderValueAfter2020, kMassachusetts,     true ],
    [kYearSliderValueAfter2020, kMaui,              false],
    [kYearSliderValueAfter2020, kMichiganMainland,  true ],
    [kYearSliderValueAfter2020, kMichiganPeninsula, true ],
    [kYearSliderValueAfter2020, kMinnesota,         true ],
    [kYearSliderValueAfter2020, kMississippi,       true ],
    [kYearSliderValueAfter2020, kMissouri,          false],
    [kYearSliderValueAfter2020, kMontana,           false],
    [kYearSliderValueAfter2020, kNebraska,          true ],
    [kYearSliderValueAfter2020, kNevada,            false],
    [kYearSliderValueAfter2020, kNewHampshire,      true ],
    [kYearSliderValueAfter2020, kNewJersey,         true ],
    [kYearSliderValueAfter2020, kNewMexico,         true ],
    [kYearSliderValueAfter2020, kNewYork,           true ],
    [kYearSliderValueAfter2020, kNorthCarolina,     false],
    [kYearSliderValueAfter2020, kNorthDakota,       false],
    [kYearSliderValueAfter2020, kOahu,              false],
    [kYearSliderValueAfter2020, kOhio,              true ],
    [kYearSliderValueAfter2020, kOklahoma,          true ],
    [kYearSliderValueAfter2020, kOregon,            false],
    [kYearSliderValueAfter2020, kPennsylvania,      true ],
    [kYearSliderValueAfter2020, kRhodeIsland,       true ],
    [kYearSliderValueAfter2020, kSouthCarolina,     true ],
    [kYearSliderValueAfter2020, kSouthDakota,       false],
    [kYearSliderValueAfter2020, kTennessee,         false],
    [kYearSliderValueAfter2020, kTexas,             true ],
    [kYearSliderValueAfter2020, kUtah,              false],
    [kYearSliderValueAfter2020, kVermont,           true ],
    [kYearSliderValueAfter2020, kVirginia,          false],
    [kYearSliderValueAfter2020, kWashington,        false],
    [kYearSliderValueAfter2020, kWestVirginia,      true ],
    [kYearSliderValueAfter2020, kWisconsin,         true ],
    [kYearSliderValueAfter2020, kWyoming,           false],
    [kYearSliderValueAfter2019, null,               false],
    [kYearSliderValueAfter2019, undefined,          false],
    [kYearSliderValueAfter2019, kAlabama,           false],
    [kYearSliderValueAfter2019, kAlaskaMainland,    false],
    [kYearSliderValueAfter2019, kArizona,           false],
    [kYearSliderValueAfter2019, kArkansas,          true ],
    [kYearSliderValueAfter2019, kCalifornia,        false],
    [kYearSliderValueAfter2019, kColorado,          true ],
    [kYearSliderValueAfter2019, kConnecticut,       false],
    [kYearSliderValueAfter2019, kDelaware,          false],
    [kYearSliderValueAfter2019, kFlorida,           false],
    [kYearSliderValueAfter2019, kGeorgia,           true ],
    [kYearSliderValueAfter2019, kHawaii,            false],
    [kYearSliderValueAfter2019, kIdaho,             false],
    [kYearSliderValueAfter2019, kIllinois,          true ],
    [kYearSliderValueAfter2019, kIndiana,           false],
    [kYearSliderValueAfter2019, kIowa,              false],
    [kYearSliderValueAfter2019, kKansas,            true ],
    [kYearSliderValueAfter2019, kKauai,             false],
    [kYearSliderValueAfter2019, kKentucky,          true ],
    [kYearSliderValueAfter2019, kKodiakIsland,      false],
    [kYearSliderValueAfter2019, kLouisiana,         true ],
    [kYearSliderValueAfter2019, kMaine,             true ],
    [kYearSliderValueAfter2019, kMaryland,          false],
    [kYearSliderValueAfter2019, kMassachusetts,     true ],
    [kYearSliderValueAfter2019, kMaui,              false],
    [kYearSliderValueAfter2019, kMichiganMainland,  true ],
    [kYearSliderValueAfter2019, kMichiganPeninsula, true ],
    [kYearSliderValueAfter2019, kMinnesota,         true ],
    [kYearSliderValueAfter2019, kMississippi,       true ],
    [kYearSliderValueAfter2019, kMissouri,          false],
    [kYearSliderValueAfter2019, kMontana,           false],
    [kYearSliderValueAfter2019, kNebraska,          true ],
    [kYearSliderValueAfter2019, kNevada,            false],
    [kYearSliderValueAfter2019, kNewHampshire,      true ],
    [kYearSliderValueAfter2019, kNewJersey,         false],
    [kYearSliderValueAfter2019, kNewMexico,         true ],
    [kYearSliderValueAfter2019, kNewYork,           true ],
    [kYearSliderValueAfter2019, kNorthCarolina,     false],
    [kYearSliderValueAfter2019, kNorthDakota,       false],
    [kYearSliderValueAfter2019, kOahu,              false],
    [kYearSliderValueAfter2019, kOhio,              false],
    [kYearSliderValueAfter2019, kOklahoma,          true ],
    [kYearSliderValueAfter2019, kOregon,            false],
    [kYearSliderValueAfter2019, kPennsylvania,      false],
    [kYearSliderValueAfter2019, kRhodeIsland,       true ],
    [kYearSliderValueAfter2019, kSouthCarolina,     true ],
    [kYearSliderValueAfter2019, kSouthDakota,       false],
    [kYearSliderValueAfter2019, kTennessee,         false],
    [kYearSliderValueAfter2019, kTexas,             true ],
    [kYearSliderValueAfter2019, kUtah,              false],
    [kYearSliderValueAfter2019, kVermont,           true ],
    [kYearSliderValueAfter2019, kVirginia,          false],
    [kYearSliderValueAfter2019, kWashington,        false],
    [kYearSliderValueAfter2019, kWestVirginia,      false],
    [kYearSliderValueAfter2019, kWisconsin,         true ],
    [kYearSliderValueAfter2019, kWyoming,           false],
    [kYearSliderValueAfter2018, null,               false],
    [kYearSliderValueAfter2018, undefined,          false],
    [kYearSliderValueAfter2018, kAlabama,           false],
    [kYearSliderValueAfter2018, kAlaskaMainland,    false],
    [kYearSliderValueAfter2018, kArizona,           false],
    [kYearSliderValueAfter2018, kArkansas,          true ],
    [kYearSliderValueAfter2018, kCalifornia,        false],
    [kYearSliderValueAfter2018, kColorado,          true ],
    [kYearSliderValueAfter2018, kConnecticut,       false],
    [kYearSliderValueAfter2018, kDelaware,          false],
    [kYearSliderValueAfter2018, kFlorida,           false],
    [kYearSliderValueAfter2018, kGeorgia,           false],
    [kYearSliderValueAfter2018, kHawaii,            false],
    [kYearSliderValueAfter2018, kIdaho,             false],
    [kYearSliderValueAfter2018, kIllinois,          false],
    [kYearSliderValueAfter2018, kIndiana,           false],
    [kYearSliderValueAfter2018, kIowa,              false],
    [kYearSliderValueAfter2018, kKansas,            false],
    [kYearSliderValueAfter2018, kKauai,             false],
    [kYearSliderValueAfter2018, kKentucky,          true ],
    [kYearSliderValueAfter2018, kKodiakIsland,      false],
    [kYearSliderValueAfter2018, kLouisiana,         true ],
    [kYearSliderValueAfter2018, kMaine,             true ],
    [kYearSliderValueAfter2018, kMaryland,          false],
    [kYearSliderValueAfter2018, kMassachusetts,     true ],
    [kYearSliderValueAfter2018, kMaui,              false],
    [kYearSliderValueAfter2018, kMichiganMainland,  false],
    [kYearSliderValueAfter2018, kMichiganPeninsula, false],
    [kYearSliderValueAfter2018, kMinnesota,         false],
    [kYearSliderValueAfter2018, kMississippi,       true ],
    [kYearSliderValueAfter2018, kMissouri,          false],
    [kYearSliderValueAfter2018, kMontana,           false],
    [kYearSliderValueAfter2018, kNebraska,          false],
    [kYearSliderValueAfter2018, kNevada,            false],
    [kYearSliderValueAfter2018, kNewHampshire,      true ],
    [kYearSliderValueAfter2018, kNewJersey,         false],
    [kYearSliderValueAfter2018, kNewMexico,         false],
    [kYearSliderValueAfter2018, kNewYork,           true ],
    [kYearSliderValueAfter2018, kNorthCarolina,     false],
    [kYearSliderValueAfter2018, kNorthDakota,       false],
    [kYearSliderValueAfter2018, kOahu,              false],
    [kYearSliderValueAfter2018, kOhio,              false],
    [kYearSliderValueAfter2018, kOklahoma,          false],
    [kYearSliderValueAfter2018, kOregon,            false],
    [kYearSliderValueAfter2018, kPennsylvania,      false],
    [kYearSliderValueAfter2018, kRhodeIsland,       true ],
    [kYearSliderValueAfter2018, kSouthCarolina,     false],
    [kYearSliderValueAfter2018, kSouthDakota,       false],
    [kYearSliderValueAfter2018, kTennessee,         false],
    [kYearSliderValueAfter2018, kTexas,             true ],
    [kYearSliderValueAfter2018, kUtah,              false],
    [kYearSliderValueAfter2018, kVermont,           true ],
    [kYearSliderValueAfter2018, kVirginia,          false],
    [kYearSliderValueAfter2018, kWashington,        false],
    [kYearSliderValueAfter2018, kWestVirginia,      false],
    [kYearSliderValueAfter2018, kWisconsin,         false],
    [kYearSliderValueAfter2018, kWyoming,           false],
    [kYearSliderValueAfter2017, null,               false],
    [kYearSliderValueAfter2017, undefined,          false],
    [kYearSliderValueAfter2017, kAlabama,           false],
    [kYearSliderValueAfter2017, kAlaskaMainland,    false],
    [kYearSliderValueAfter2017, kArizona,           false],
    [kYearSliderValueAfter2017, kArkansas,          false],
    [kYearSliderValueAfter2017, kCalifornia,        false],
    [kYearSliderValueAfter2017, kColorado,          false],
    [kYearSliderValueAfter2017, kConnecticut,       false],
    [kYearSliderValueAfter2017, kDelaware,          false],
    [kYearSliderValueAfter2017, kFlorida,           false],
    [kYearSliderValueAfter2017, kGeorgia,           false],
    [kYearSliderValueAfter2017, kHawaii,            false],
    [kYearSliderValueAfter2017, kIdaho,             false],
    [kYearSliderValueAfter2017, kIllinois,          false],
    [kYearSliderValueAfter2017, kIndiana,           false],
    [kYearSliderValueAfter2017, kIowa,              false],
    [kYearSliderValueAfter2017, kKansas,            false],
    [kYearSliderValueAfter2017, kKauai,             false],
    [kYearSliderValueAfter2017, kKentucky,          true ],
    [kYearSliderValueAfter2017, kKodiakIsland,      false],
    [kYearSliderValueAfter2017, kLouisiana,         false],
    [kYearSliderValueAfter2017, kMaine,             false],
    [kYearSliderValueAfter2017, kMaryland,          false],
    [kYearSliderValueAfter2017, kMassachusetts,     true ],
    [kYearSliderValueAfter2017, kMaui,              false],
    [kYearSliderValueAfter2017, kMichiganMainland,  false],
    [kYearSliderValueAfter2017, kMichiganPeninsula, false],
    [kYearSliderValueAfter2017, kMinnesota,         false],
    [kYearSliderValueAfter2017, kMississippi,       false],
    [kYearSliderValueAfter2017, kMissouri,          false],
    [kYearSliderValueAfter2017, kMontana,           false],
    [kYearSliderValueAfter2017, kNebraska,          false],
    [kYearSliderValueAfter2017, kNevada,            false],
    [kYearSliderValueAfter2017, kNewHampshire,      true ],
    [kYearSliderValueAfter2017, kNewJersey,         false],
    [kYearSliderValueAfter2017, kNewMexico,         false],
    [kYearSliderValueAfter2017, kNewYork,           false],
    [kYearSliderValueAfter2017, kNorthCarolina,     false],
    [kYearSliderValueAfter2017, kNorthDakota,       false],
    [kYearSliderValueAfter2017, kOahu,              false],
    [kYearSliderValueAfter2017, kOhio,              false],
    [kYearSliderValueAfter2017, kOklahoma,          false],
    [kYearSliderValueAfter2017, kOregon,            false],
    [kYearSliderValueAfter2017, kPennsylvania,      false],
    [kYearSliderValueAfter2017, kRhodeIsland,       false],
    [kYearSliderValueAfter2017, kSouthCarolina,     false],
    [kYearSliderValueAfter2017, kSouthDakota,       false],
    [kYearSliderValueAfter2017, kTennessee,         false],
    [kYearSliderValueAfter2017, kTexas,             true ],
    [kYearSliderValueAfter2017, kUtah,              false],
    [kYearSliderValueAfter2017, kVermont,           false],
    [kYearSliderValueAfter2017, kVirginia,          false],
    [kYearSliderValueAfter2017, kWashington,        false],
    [kYearSliderValueAfter2017, kWestVirginia,      false],
    [kYearSliderValueAfter2017, kWisconsin,         false],
    [kYearSliderValueAfter2017, kWyoming,           false],
    [kYearSliderValueAfter2016, null,               false],
    [kYearSliderValueAfter2016, undefined,          false],
    [kYearSliderValueAfter2016, kAlabama,           false],
    [kYearSliderValueAfter2016, kAlaskaMainland,    false],
    [kYearSliderValueAfter2016, kArizona,           false],
    [kYearSliderValueAfter2016, kArkansas,          false],
    [kYearSliderValueAfter2016, kCalifornia,        false],
    [kYearSliderValueAfter2016, kColorado,          false],
    [kYearSliderValueAfter2016, kConnecticut,       false],
    [kYearSliderValueAfter2016, kDelaware,          false],
    [kYearSliderValueAfter2016, kFlorida,           false],
    [kYearSliderValueAfter2016, kGeorgia,           false],
    [kYearSliderValueAfter2016, kHawaii,            false],
    [kYearSliderValueAfter2016, kIdaho,             false],
    [kYearSliderValueAfter2016, kIllinois,          false],
    [kYearSliderValueAfter2016, kIndiana,           false],
    [kYearSliderValueAfter2016, kIowa,              false],
    [kYearSliderValueAfter2016, kKansas,            false],
    [kYearSliderValueAfter2016, kKauai,             false],
    [kYearSliderValueAfter2016, kKentucky,          false],
    [kYearSliderValueAfter2016, kKodiakIsland,      false],
    [kYearSliderValueAfter2016, kLouisiana,         false],
    [kYearSliderValueAfter2016, kMaine,             false],
    [kYearSliderValueAfter2016, kMaryland,          false],
    [kYearSliderValueAfter2016, kMassachusetts,     true ],
    [kYearSliderValueAfter2016, kMaui,              false],
    [kYearSliderValueAfter2016, kMichiganMainland,  false],
    [kYearSliderValueAfter2016, kMichiganPeninsula, false],
    [kYearSliderValueAfter2016, kMinnesota,         false],
    [kYearSliderValueAfter2016, kMississippi,       false],
    [kYearSliderValueAfter2016, kMissouri,          false],
    [kYearSliderValueAfter2016, kMontana,           false],
    [kYearSliderValueAfter2016, kNebraska,          false],
    [kYearSliderValueAfter2016, kNevada,            false],
    [kYearSliderValueAfter2016, kNewHampshire,      true ],
    [kYearSliderValueAfter2016, kNewJersey,         false],
    [kYearSliderValueAfter2016, kNewMexico,         false],
    [kYearSliderValueAfter2016, kNewYork,           false],
    [kYearSliderValueAfter2016, kNorthCarolina,     false],
    [kYearSliderValueAfter2016, kNorthDakota,       false],
    [kYearSliderValueAfter2016, kOahu,              false],
    [kYearSliderValueAfter2016, kOhio,              false],
    [kYearSliderValueAfter2016, kOklahoma,          false],
    [kYearSliderValueAfter2016, kOregon,            false],
    [kYearSliderValueAfter2016, kPennsylvania,      false],
    [kYearSliderValueAfter2016, kRhodeIsland,       false],
    [kYearSliderValueAfter2016, kSouthCarolina,     false],
    [kYearSliderValueAfter2016, kSouthDakota,       false],
    [kYearSliderValueAfter2016, kTennessee,         false],
    [kYearSliderValueAfter2016, kTexas,             true ],
    [kYearSliderValueAfter2016, kUtah,              false],
    [kYearSliderValueAfter2016, kVermont,           false],
    [kYearSliderValueAfter2016, kVirginia,          false],
    [kYearSliderValueAfter2016, kWashington,        false],
    [kYearSliderValueAfter2016, kWestVirginia,      false],
    [kYearSliderValueAfter2016, kWisconsin,         false],
    [kYearSliderValueAfter2016, kWyoming,           false],
    [kYearSliderValueAfter2015, null,               false],
    [kYearSliderValueAfter2015, undefined,          false],
    [kYearSliderValueAfter2015, kAlabama,           false],
    [kYearSliderValueAfter2015, kAlaskaMainland,    false],
    [kYearSliderValueAfter2015, kArizona,           false],
    [kYearSliderValueAfter2015, kArkansas,          false],
    [kYearSliderValueAfter2015, kCalifornia,        false],
    [kYearSliderValueAfter2015, kColorado,          false],
    [kYearSliderValueAfter2015, kConnecticut,       false],
    [kYearSliderValueAfter2015, kDelaware,          false],
    [kYearSliderValueAfter2015, kFlorida,           false],
    [kYearSliderValueAfter2015, kGeorgia,           false],
    [kYearSliderValueAfter2015, kHawaii,            false],
    [kYearSliderValueAfter2015, kIdaho,             false],
    [kYearSliderValueAfter2015, kIllinois,          false],
    [kYearSliderValueAfter2015, kIndiana,           false],
    [kYearSliderValueAfter2015, kIowa,              false],
    [kYearSliderValueAfter2015, kKansas,            false],
    [kYearSliderValueAfter2015, kKauai,             false],
    [kYearSliderValueAfter2015, kKentucky,          false],
    [kYearSliderValueAfter2015, kKodiakIsland,      false],
    [kYearSliderValueAfter2015, kLouisiana,         false],
    [kYearSliderValueAfter2015, kMaine,             false],
    [kYearSliderValueAfter2015, kMaryland,          false],
    [kYearSliderValueAfter2015, kMassachusetts,     false],
    [kYearSliderValueAfter2015, kMaui,              false],
    [kYearSliderValueAfter2015, kMichiganMainland,  false],
    [kYearSliderValueAfter2015, kMichiganPeninsula, false],
    [kYearSliderValueAfter2015, kMinnesota,         false],
    [kYearSliderValueAfter2015, kMississippi,       false],
    [kYearSliderValueAfter2015, kMissouri,          false],
    [kYearSliderValueAfter2015, kMontana,           false],
    [kYearSliderValueAfter2015, kNebraska,          false],
    [kYearSliderValueAfter2015, kNevada,            false],
    [kYearSliderValueAfter2015, kNewHampshire,      true ],
    [kYearSliderValueAfter2015, kNewJersey,         false],
    [kYearSliderValueAfter2015, kNewMexico,         false],
    [kYearSliderValueAfter2015, kNewYork,           false],
    [kYearSliderValueAfter2015, kNorthCarolina,     false],
    [kYearSliderValueAfter2015, kNorthDakota,       false],
    [kYearSliderValueAfter2015, kOahu,              false],
    [kYearSliderValueAfter2015, kOhio,              false],
    [kYearSliderValueAfter2015, kOklahoma,          false],
    [kYearSliderValueAfter2015, kOregon,            false],
    [kYearSliderValueAfter2015, kPennsylvania,      false],
    [kYearSliderValueAfter2015, kRhodeIsland,       false],
    [kYearSliderValueAfter2015, kSouthCarolina,     false],
    [kYearSliderValueAfter2015, kSouthDakota,       false],
    [kYearSliderValueAfter2015, kTennessee,         false],
    [kYearSliderValueAfter2015, kTexas,             false],
    [kYearSliderValueAfter2015, kUtah,              false],
    [kYearSliderValueAfter2015, kVermont,           false],
    [kYearSliderValueAfter2015, kVirginia,          false],
    [kYearSliderValueAfter2015, kWashington,        false],
    [kYearSliderValueAfter2015, kWestVirginia,      false],
    [kYearSliderValueAfter2015, kWisconsin,         false],
    [kYearSliderValueAfter2015, kWyoming,           false],
    [kYearSliderValueAfter2014, null,               false],
    [kYearSliderValueAfter2014, undefined,          false],
    [kYearSliderValueAfter2014, kAlabama,           false],
    [kYearSliderValueAfter2014, kAlaskaMainland,    false],
    [kYearSliderValueAfter2014, kArizona,           false],
    [kYearSliderValueAfter2014, kArkansas,          false],
    [kYearSliderValueAfter2014, kCalifornia,        false],
    [kYearSliderValueAfter2014, kColorado,          false],
    [kYearSliderValueAfter2014, kConnecticut,       false],
    [kYearSliderValueAfter2014, kDelaware,          false],
    [kYearSliderValueAfter2014, kFlorida,           false],
    [kYearSliderValueAfter2014, kGeorgia,           false],
    [kYearSliderValueAfter2014, kHawaii,            false],
    [kYearSliderValueAfter2014, kIdaho,             false],
    [kYearSliderValueAfter2014, kIllinois,          false],
    [kYearSliderValueAfter2014, kIndiana,           false],
    [kYearSliderValueAfter2014, kIowa,              false],
    [kYearSliderValueAfter2014, kKansas,            false],
    [kYearSliderValueAfter2014, kKauai,             false],
    [kYearSliderValueAfter2014, kKentucky,          false],
    [kYearSliderValueAfter2014, kKodiakIsland,      false],
    [kYearSliderValueAfter2014, kLouisiana,         false],
    [kYearSliderValueAfter2014, kMaine,             false],
    [kYearSliderValueAfter2014, kMaryland,          false],
    [kYearSliderValueAfter2014, kMassachusetts,     false],
    [kYearSliderValueAfter2014, kMaui,              false],
    [kYearSliderValueAfter2014, kMichiganMainland,  false],
    [kYearSliderValueAfter2014, kMichiganPeninsula, false],
    [kYearSliderValueAfter2014, kMinnesota,         false],
    [kYearSliderValueAfter2014, kMississippi,       false],
    [kYearSliderValueAfter2014, kMissouri,          false],
    [kYearSliderValueAfter2014, kMontana,           false],
    [kYearSliderValueAfter2014, kNebraska,          false],
    [kYearSliderValueAfter2014, kNevada,            false],
    [kYearSliderValueAfter2014, kNewHampshire,      false],
    [kYearSliderValueAfter2014, kNewJersey,         false],
    [kYearSliderValueAfter2014, kNewMexico,         false],
    [kYearSliderValueAfter2014, kNewYork,           false],
    [kYearSliderValueAfter2014, kNorthCarolina,     false],
    [kYearSliderValueAfter2014, kNorthDakota,       false],
    [kYearSliderValueAfter2014, kOahu,              false],
    [kYearSliderValueAfter2014, kOhio,              false],
    [kYearSliderValueAfter2014, kOklahoma,          false],
    [kYearSliderValueAfter2014, kOregon,            false],
    [kYearSliderValueAfter2014, kPennsylvania,      false],
    [kYearSliderValueAfter2014, kRhodeIsland,       false],
    [kYearSliderValueAfter2014, kSouthCarolina,     false],
    [kYearSliderValueAfter2014, kSouthDakota,       false],
    [kYearSliderValueAfter2014, kTennessee,         false],
    [kYearSliderValueAfter2014, kTexas,             false],
    [kYearSliderValueAfter2014, kUtah,              false],
    [kYearSliderValueAfter2014, kVermont,           false],
    [kYearSliderValueAfter2014, kVirginia,          false],
    [kYearSliderValueAfter2014, kWashington,        false],
    [kYearSliderValueAfter2014, kWestVirginia,      false],
    [kYearSliderValueAfter2014, kWisconsin,         false],
    [kYearSliderValueAfter2014, kWyoming,           false]
];

test(`given a primitive value with no attributes, tomHasHighPointedStateWithinSliderRange()
        returns false`, () => {
    const primitiveValue = "primitiveValue";
    expect(tomHasHighPointedStateWithinSliderRange(primitiveValue)).toBe(false);
}); /* given a primitive value with no attributes, tomHasHighPointedStateWithinSliderRange()
        returns false */

describe(`validate results of tomHasHighPointedStateWithinSliderRange() with expected
        inputs`, () => {
    each(kInputAndExpectedOutputSets).it(
            `case showing that year '%s' and state '%s' returns '%s'`,
            (sliderValue, stateId, expectedOutput) => {
        onPageLoad();
        changeValueOfSliderThumb(sliderValue);
        const state = document.getElementById(stateId);

        const actualOutput = tomHasHighPointedStateWithinSliderRange(state);

        expect(actualOutput).toBe(expectedOutput);
    });
}); /* validate results of tomHasHighPointedStateWithinSliderRange() with expected
        inputs */
